# Generated by Django 3.2.16 on 2023-03-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('i_d', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pro', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('water', models.IntegerField()),
                ('fats', models.IntegerField()),
            ],
        ),
    ]
