# Generated by Django 3.2.16 on 2023-03-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_logins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logins',
            new_name='login',
        ),
    ]
