# Generated by Django 3.2.16 on 2023-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_rename_logins_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='diet',
            fields=[
                ('i_d', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pro', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('water', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('i_d', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('plan_no', models.IntegerField()),
                ('current_w', models.IntegerField()),
                ('target_w', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
